services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrovida-laravel
    volumes:
      - .:/var/www
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - agrovida-net
      - internal-network

  nginx:
    image: nginx:latest
    container_name: agrovida-nginx
    expose:
      - "80"
    # ports:
    #   - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - agrovida-net
      - proxy-network

  db:
    image: postgres:16
    container_name: agrovida-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mercado_agricola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - agrovida-net

networks:
  agrovida-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data:
